#page title
page_title                                : InkSpire - Your Tattoo Inspiration Hub

# App Info
ios_app_id                                : 1234793120                                
ios_app_country                           : us                                        

appstore_link                             : # Automatically populates

app_icon                                  : assets/appicon.png                     
app_name                                  : InkSpire
app_price                                 : Free
app_description                           : Discover and create amazing tattoo designs with InkSpire. Get inspired, try tattoos virtually, and soon, create your own tattoos using AI.

enable_smart_app_banner                   : true                                      



# Information About Yourself
your_name                                 : Lucas Saldanha                               
email_address                             : inkspiretechcontact@gmail.com
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : 
github_username                           : 
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Get Inspired
    description                           : Browse thousands of unique tattoo designs. Save your favorites and create a personalized inspiration collection.
    fontawesome_icon_name                 : magic
    
  - title                                 : Try Tattoos Virtually
    description                           : Use your phone's camera to try on tattoos before making the commitment. Find the perfect design for your style.
    fontawesome_icon_name                 : mobile

  - title                                 : AI Tattoo Creation
    description                           : Coming soon. Design your unique tattoo with our AI technology. Create something truly personal and one-of-a-kind.
    fontawesome_icon_name                 : brain

# Theme Settings
topbar_color                              : "#2C2C2C"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    
cover_overlay_color                       : "#2C2C2C"
cover_overlay_transparency                : 1.0

device_color                              : black                                     

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#2C2C2C2C"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#2C2C2C2C"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"


####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
